# Generated by Django 5.1.3 on 2024-11-29 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='users/profile_pictures')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='users/cover_photo')),
                ('address_line_1', models.CharField(blank=True, max_length=50, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, choices=[('India', 'India')], max_length=20)),
                ('state', models.CharField(blank=True, choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('others', 'others')], max_length=20)),
                ('city', models.CharField(blank=True, choices=[('Visakhapatnam', 'Visakhapatnam'), ('Vijayawada', 'Vijayawada'), ('Tirupati', 'Tirupati'), ('Guwahati', 'Guwahati'), ('Dibrugarh', 'Dibrugarh'), ('Silchar', 'Silchar'), ('Patna', 'Patna'), ('Gaya', 'Gaya'), ('Bhagalpur', 'Bhagalpur'), ('Raipur', 'Raipur'), ('Bilaspur', 'Bilaspur'), ('Durg', 'Durg'), ('New Delhi', 'New Delhi'), ('Dwarka', 'Dwarka'), ('Saket', 'Saket'), ('Panaji', 'Panaji'), ('Margao', 'Margao'), ('Vasco da Gama', 'Vasco da Gama'), ('Ahmedabad', 'Ahmedabad'), ('Surat', 'Surat'), ('Vadodara', 'Vadodara'), ('Gurgaon', 'Gurgaon'), ('Faridabad', 'Faridabad'), ('Panchkula', 'Panchkula'), ('Shimla', 'Shimla'), ('Manali', 'Manali'), ('Dharamshala', 'Dharamshala'), ('Ranchi', 'Ranchi'), ('Jamshedpur', 'Jamshedpur'), ('Dhanbad', 'Dhanbad'), ('Bengaluru', 'Bengaluru'), ('Mysuru', 'Mysuru'), ('Mangaluru', 'Mangaluru'), ('Kochi', 'Kochi'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kozhikode', 'Kozhikode'), ('Bhopal', 'Bhopal'), ('Indore', 'Indore'), ('Gwalior', 'Gwalior'), ('Mumbai', 'Mumbai'), ('Pune', 'Pune'), ('Nagpur', 'Nagpur'), ('Imphal', 'Imphal'), ('Churachandpur', 'Churachandpur'), ('Ukhrul', 'Ukhrul'), ('Shillong', 'Shillong'), ('Cherrapunji', 'Cherrapunji'), ('Tura', 'Tura'), ('Aizawl', 'Aizawl'), ('Lunglei', 'Lunglei'), ('Champhai', 'Champhai'), ('Kohima', 'Kohima'), ('Dimapur', 'Dimapur'), ('Mokokchung', 'Mokokchung'), ('Bhubaneswar', 'Bhubaneswar'), ('Cuttack', 'Cuttack'), ('Rourkela', 'Rourkela'), ('Amritsar', 'Amritsar'), ('Chandigarh', 'Chandigarh'), ('Ludhiana', 'Ludhiana'), ('Jaipur', 'Jaipur'), ('Udaipur', 'Udaipur'), ('Jodhpur', 'Jodhpur'), ('Gangtok', 'Gangtok'), ('Pelling', 'Pelling'), ('Mangan', 'Mangan'), ('Chennai', 'Chennai'), ('Coimbatore', 'Coimbatore'), ('Madurai', 'Madurai'), ('Hyderabad', 'Hyderabad'), ('Warangal', 'Warangal'), ('Khammam', 'Khammam'), ('Agartala', 'Agartala'), ('Udaipur', 'Udaipur'), ('Ambassa', 'Ambassa'), ('Lucknow', 'Lucknow'), ('Kanpur', 'Kanpur'), ('Allahabad', 'Allahabad'), ('Mangalore', 'Mangalore'), ('Hassan', 'Hassan'), ('Chikmagalur', 'Chikmagalur'), ('Kolkata', 'Kolkata'), ('Howrah', 'Howrah'), ('Siliguri', 'Siliguri'), ('Lucknow', 'Lucknow'), ('Agra', 'Agra'), ('Kanpur', 'Kanpur'), ('Chandigarh', 'Chandigarh'), ('Faridabad', 'Faridabad'), ('Mohali', 'Mohali'), ('others', 'others')], max_length=50)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
