# Generated by Django 5.1.3 on 2024-12-05 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_is_active_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_freeze',
            field=models.BooleanField(default=False),
        ),
    ]
