# Generated by Django 5.1.3 on 2025-01-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_location'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['location'], name='accounts_us_locatio_56d68c_idx'),
        ),
    ]
