# Generated by Django 5.1.3 on 2025-01-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_accounts_us_locatio_56d68c_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userprofile',
            name='accounts_us_locatio_56d68c_idx',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
