# Generated by Django 5.1.3 on 2024-12-17 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_category_options_fooditem_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='Category',
            new_name='category',
        ),
    ]
