# Generated by Django 5.1.3 on 2025-01-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_category_slug_alter_fooditem_slug'),
        ('vendor', '0005_alter_vendor_slug'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('vendor', 'category_name'), name='unique_vendor_category'),
        ),
    ]
