# Generated by Django 5.1.3 on 2025-01-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_category_unique_vendor_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=40),
        ),
    ]
